"""Semantic chunking constants aligned with Iris-Main Features/Semantic."""

CHUNK_DURATION_SECONDS = 4.0
CHUNK_OVERLAP_SECONDS = 0.5
CHUNK_STRIDE_SECONDS = max(0.1, CHUNK_DURATION_SECONDS - CHUNK_OVERLAP_SECONDS)
CHUNK_TOP_K = 10
CHUNK_MERGE_MINIMUM_SCORE = 0.15
RANGE_MERGE_GAP_SECONDS = 0.6
RESULTS_LIMIT = 3
